# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13c8T2CrCtMhc1rUXpyZXRPsYF4RH7ojJ
"""

import numpy as np
from scipy.stats import bernoulli

sample_size=10000
no_male=np.size(np.nonzero(bernoulli.rvs(size=sample_size,p=0.5)))
no_female=sample_size-no_male

print("no.of male in the group = {} |||".format(no_male),"no.of female in the group {} ".format(no_female),"\n")

male_gray_prob=0.05
female_gray_prob=0.0025

#simulating the no.of gray haired persons in male and female
data_bern_male=bernoulli.rvs(size=no_male,p=male_gray_prob)
data_bern_female=bernoulli.rvs(size=no_female,p=female_gray_prob)

#getting the no.of gray haired male and female
gray_male=np.nonzero(data_bern_male)
gray_female=np.nonzero(data_bern_female)
no_gray_male=np.size(gray_male)
no_gray_female=np.size(gray_female)

print("no.of gray male in the group = {} |||".format(size_gray_male),"no.of gray female in the group = {}".format(size_gray_female),"\n")

#calculating the probability that the selected gray haired person is male
total_gray_people=no_gray_female+no_gray_male
prob_male=no_gray_male/total_gray_people

print("Experimental probability that the selected gray haired person is male = {}".format(prob_male))
print("Theoritical probability that the selected gray haired person is male = {}".format(0.952380952),"\n")
print("Experimental and theoritical probability are approximately equal.")