# -*- coding: utf-8 -*-
"""Assignment8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LbUpvNyTZ6qFHaKWOOkHeb2sZgD2i8dt
"""

import numpy as np
from scipy.stats import poisson

#no. of time intervals 
sample_size=100000

#simulating jobs arrival at workstation
arrival_data=poisson.rvs(mu=12,size=sample_size)
#simulating jobs completion at workstation
service_data=poisson.rvs(mu=15,size=sample_size)
#print(arrival_data-service_data)

#calculating jobs at workstation
jobs_at_machine=[0]
for x in range(1,sample_size):
    jobs_tentative=jobs_at_machine[x-1]+arrival_data[x]-service_data[x]
    if jobs_tentative>=0:
      jobs_at_machine.append(jobs_tentative)
    else:
        jobs_at_machine.append(jobs_at_machine[x-1])
print("Experimental and Theoritical Expectation value of jobs at workstation  {}--{}".format(np.sum(jobs_at_machine)/sample_size,4))