# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17XNKdfUZPQYKY3b8PEus6oTXf5WWKKZS
"""

import numpy as np
from scipy.stats import bernoulli

sample_size=100000
err=0
n=5 #no.of trails
k=3 #k is no.of required heads

#generating n trail tossing random process and counting favourable outcomes
for x in range(sample_size):
  trail=bernoulli.rvs(p=0.5,size=n)
  if trail[n-1]==1 and np.sum(trail)==k:
      err+=1

#favourable outcome is 5th toss resulting in the third head
print("Experimental probability and theoritcal probability for the favourable outcome are {}---{}".format(err/sample_size,6/32))